language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - 8.1
  - 8.2
  - 8.3
  - 8.4

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  slack:
    secure: imJwHsdEHDW7Q5M73Xef78ve97sNhrBzWSoZvKB5ZumGVAnj6vfrcOwrx2k045COrrRMwindnQ2HgQoJMI35dLVAHSQzlaFa7sNC5ATHz8HZxbTivT5yP/UzrQ9lyXDlwdtamQybaBwEuz6+VusuSoCiY7Q+36QclpcrliK8z4qiACDPY96Nl0OcahkTiw9Z3rOiUySoz3Cr1ZNxgTeBZCBJ0PLGUGVyoUwDxRQdMytGwLSInDl4hEyh38YaQLJyXN7oTnLqG/rDw2WUwnccsOf8RXQQwPf+soTC8+/T0AYOVqFZhZPOO8mgsrx+9MYTOhnVEWW83lNPwilvdj1cK2MiqA7VckzIRU7lnC1M3nJVElPaGz4WMnaStmgcaBD+NnQHEPMYNDl8xR63VUZfAsBXhjdVVKmjs3bH6C1Do0o/96erYxc1DMYpKm7EM2rAdUl4dTjYD7hHzDLbOIBB2iCsoMo5lLWkKzNHZRLNbTYDycAagfKGFBEso05HSFZdwjQYz37eMfZVYluP/1HHGwOmfPXnKJIcQXe2vxE7RFpxBDqscLgcC94TVeVjUXhnontVFGVsc6D2FhF0IjuHGjpTOmDoXXwRLF5gJ+5zVZJGA1lMwW7Qm5ediBSErIClGv202j0VkVBkbswhbD8wXJWcRl7j4URhIh1p1MHM7A0=
